apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv  # Name of the PersistentVolume
spec:
  capacity:
    storage: 10Gi  # Size of the volume
  accessModes:
    - ReadWriteOnce  # Access mode (can be ReadWriteOnce, ReadOnlyMany, or ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # What happens to the volume when the PVC is deleted (Retain, Delete, or Recycle)
  storageClassName: manual  # Optional: Name of the StorageClass (if not specified, it will use the default StorageClass)
  hostPath:
    path: /opt/wordpress
